name: virex_observability
description: Observability and telemetry adapters for Virex inspector events.
version: 0.1.0
publish_to: none
homepage: https://github.com/virex-dev/virex
repository: https://github.com/virex-dev/virex
issue_tracker: https://github.com/virex-dev/virex/issues

environment:
  sdk: ^3.10.0

dependencies:
  virex:
    path: ../../

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
