name: virex_riverpod_bridge
description: Riverpod interoperability bridges for Virex.
version: 0.1.0
publish_to: none
homepage: https://github.com/virex-dev/virex
repository: https://github.com/virex-dev/virex
issue_tracker: https://github.com/virex-dev/virex/issues

environment:
  sdk: ^3.10.0

dependencies:
  riverpod: ^2.6.1
  virex:
    path: ../../

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
